[workspace]

members = ["client"]


[package]
name = "sessions"
version = "0.1.0"
edition = "2021"

[dependencies]
sessions-app = { path = "app" }

[build-dependencies]
sessions-app = { path = "app" }
sails-rs = { version = "0.4.0", features = ["wasm-builder"] }
sails-idl-gen = "0.4.0"

[dev-dependencies]
sessions = { path = ".", features = ["wasm-binary"] }
sessions-client = { path = "client" }
sails-rs = { version = "0.4.0", features = ["gtest"] }
tokio = { version = "1.39", features = ["rt", "macros"] }

[features]
wasm-binary = []
